### ISSUE TITLE
SDL2.0 doesn't exist

### ISSUE THREAD

**Issue by iamlanjt** [Lokathor/beryllium#115]
OS: Windows 10 64-bit

├── beryllium v0.2.1
│   └── fermium v0.1.4
├── bytemuck v1.9.1
├── imagine v0.0.5
│   └── bytemuck v1.9.1
└── ogl33 v0.2.0

I was told in a help forum by a user that fermium was supposed to handle SDL2.0 for me but it doesn't
> This crate bundles a copy of the SDL2 source code and builds it automatically via build.rs. No special setup is required on your part.
>
> Building SDL2 takes about a minute on an average development machine, so the “first time” compilation of this crate can seem quite slow.

I got it to work by just dropping the ``SDL2.dll`` file (from http://www.libsdl.org/download-2.0.php) but they still told me to open an issue
Cargo.toml (also tried v0.2.0-alpha.4 but that didnt work either)
```toml
[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
beryllium = "0.2.0-alpha.2"
imagine = "0.0.5"
```
code
https://rust-tutorials.github.io/learn-opengl/basics/000-creating-a-window.html
![Screenshot_150](https://user-images.githubusercontent.com/74612839/170918317-aedb5311-828f-4c85-92c0-2ffe2a3a9fe1.png)
